baseURL: "https://dingning-zhang.github.io/" 
title: Dingning Zhang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 2 
        - name: Publications
          url: publications/
          weight: 3
        - name: Presentations
          url: presentations/
          weight: 4
        - name: Teaching
          url: teaching/
          weight: 5 
        - name: Outreach
          url: outreach/
          weight: 6

params:
    description: "This website hosts Dingning Zhang's research papers, presentations, course materials, curriculum vitae, and contact information."
    author: Dingning Zhang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "December 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dingning Zhang
          subtitle: "Dingning Zhang 张丁宁 is a predoctoral researcher in the PhD programme of Cognitive Science and Language at the University of Barcelona. His research interests include experimental phonetics, sociolinguistics, second language acquisition, psycholinguistics and neural mechanisms of language"
          imageUrl: "Joey.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Publications
              url: publications/
            - name: Presentations
              url: data/
            - name: Teaching
              url: courses/
            - name: Outreach
              url: outreach/

    socialIcons:
        - name: CV
          url: /CV.pdf
        - name: Email
          url: "mailto:dnzhang@ub.edu"
        - name: website
          url: "https://linguistica.ub.edu/directori-organitzatiu/dingning-zhang"
        - name: ORCID
          url: "https://orcid.org/0009-0000-6040-5390"
        - name: Google Scholar
          url: "https://scholar.google.com/citations?&user=R2TnSeEAAAAJ"
        - name: Zoom
          url: "https://us05web.zoom.us/j/8699596744?pwd=NlBxL21aOUZsUWJzd0Z2YklaSVBiUT09"
        - name: GitHub
          url: "https://github.com/dingning-zhang"
        - name: Linkedin
          url: "https://www.linkedin.com/in/joey-zhang-95416329a/"
        - name: Twitter
          url: "https://x.com/DingningZhangOf"
        - name: Bluesky
          url: "https://bsky.app/profile/dingningzhang.bsky.social"

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dingning Zhang"
      icon: Joey.jpg
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
